---
- hosts: redis-cluster-server 
  sudo: yes
  vars:
    redis_dir: /root/redis
    redis_port: 7000
  tasks:
    - name: download install src
      get_url: url=http://download.redis.io/releases/redis-3.0.1.tar.gz dest=/tmp

    - name: unarchive src file
      unarchive: src=/tmp/redis-3.0.1.tar.gz dest=/tmp

    - name: create a directory
      file: path={{ redis_dir }}/{{ redis_port }} state=directory

    - name: set conf
      template: src=template/redis.conf.j2 dest={{ redis_dir }}/{{ redis_port }}/redis.conf
