---
- hosts: redis-cluster-server 
  sudo: yes
  vars:
    ruby_home: /usr/local/ruby
    tmp_dir: /tmp
    ruby_src_dir: /tmp/ruby-2.2.2
  tasks:
    - name: check ruby install
      command: /usr/local/ruby/bin/ruby --version
      ignore_errors: True
      register: isInstallRuby
      changed_when: false
      always_run: yes

#    - debug: var=isInstallRedis.stdout_lines

    - name: download install src
      get_url: url=http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.2.tar.gz dest={{ tmp_dir }}

    - name: unarchive src file
      unarchive: src={{ tmp_dir }}/ruby-2.2.2.tar.gz dest={{ tmp_dir }}

    - name: configure ruby src
      command: chdir={{ ruby_src_dir }} ./configure --prefix={{ ruby_home }}
      when: isInstallRuby|failed

    - name: make ruby src
      command: chdir={{ ruby_src_dir }} make
      when: isInstallRuby|failed

    - name: make install ruby
      command: chdir={{ ruby_src_dir }} make install
      when: isInstallRuby|failed

    - name: export path
      lineinfile: dest=/root/.bash_profile line='export PATH={{ ruby_home }}/bin:$PATH'

#    - name: start redis-server
#      shell: chdir={{ redis_dir }}/{{ redis_port }} /usr/local/bin/redis-server redis.conf &>/dev/null &

    - name: install yum packages
      yum: name={{ item }} state=latest
      with_items:
        - libffi-devel
        - zlib-devel
        - openssl-devel

